name = input("Name:")
print(name)
age = input("Age:")
print( age)
city = input("City:")
print(city)
Work_Area = input("School:")
print( Work_Area)
work = input("Profession:")
print( work)
animal = input("Pet:")
print( animal)