print("Responde las siguientes preguntas")
name=input("Cual es tu nombre?")
edad=input("Cual es tu edad?")
ciudad=input("En que cuidad vives?")
EstudioGeneral=input("En que universidad o colegio estudiaste?")
Prefesion=input("Cual es tu profesion?")
Mascota=input("Cual es el nombre de tu mascota?")
print("ESTAS SON TUS RESPUESTAS")
print("Cual es tu nombre:" ,name, "/ Cual es tu edad:" ,edad , "/ En que cuidad vives:" , ciudad , "/ En que universidad o colegio estudiaste:" ,EstudioGeneral , "/ Cual es tu profesion:" , Prefesion , "/ Cual es el nombre de tu mascota:" , Mascota)