userName = input(" Enter user's name:")
userAge = input(" Enter user's age:")
userCity = input(" Enter user's city:")
userCollege = input(" Enter user's college:")
userProfession = input(" Enter user's profession:")
userPet = input(" Enter user's pet name:")

print ("There once was a person named",userName, end="")
print (" who lived in", userCity, end="")
print (". At the age of", userAge, end="")
print (",",userName, end="")
print (" went to college at" ,userCollege, end="")
print (".", userName, end="")
print (" graduated and went to work as a",userProfession, end="")
print (". Then,", userName, end="")
print (" adopted an animal named", userPet, end="")
print (". They both lived happily ever after!")